version: "3.5"

services:
  gds-compile-task:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./build:/app/build
    command: >
      ./gradlew :open-packaging:shadowCopy